In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('goodreads/books_2.csv')

data.head()

,BookID,Title,Author,Rating,Number of raters,5 stars,4 stars,3 stars,2 stars,1 star,Number of reviewers,Pages,PublishDate,Book format,Language,GenreLink,Series
0,100001,Stephen Hawking's Universe,John Boslough,4.03,748,272,279,147,46,4,39,127.0,July 1st 1984,Paperback,English,6153,NaN
1,100002,Beyond The Black Hole: Stephen Hawking's Universe,John Boslough,4.03,748,272,279,147,46,4,39,144.0,July 1st 1984,Hardcover,NaN,6153,NaN
2,100005,In Search of Schrödinger's Cat,John Gribbin,4.05,18783,7027,6927,3753,800,276,473,302.0,September 1984,Paperback,English,96418,Schrödinger's Cat
3,100006,Schrödinger's Kittens and the Search for Reali...,"John Gribbin, Mark Evan Chimsky",4.06,1500,534,601,300,48,17,60,272.0,1984,Paperback,English,208911,Schrödinger's Cat
4,100015,Bahama Crisis,Desmond Bagley,3.63,461,79,181,157,38,6,21,NaN,January 1st 1981,Audio Cassette,English,96428,NaN

In [3]:
len(data)

33560

In [4]:
clean_v1 = data[~data.GenreLink.isnull()]

len(clean_v1)

33560

In [5]:
clean_v2 = clean_v1.drop_duplicates(subset="BookID")
len(clean_v2)

33560

In [16]:
clean_v3 = clean_v2[clean_v2["Number of raters"] > 150]
len(clean_v3)

33560

In [9]:
publish = clean_v3.PublishDate
year = publish.str.split().str[-1]
year

0        1984
1        1984
2        1984
3        1984
4        1981
         ...
33555    1972
33556    1962
33557    2003
33558    1972
33559    1962
Name: PublishDate, Length: 33560, dtype: object

In [13]:
noise = list(year[~year.str.isdigit()].index)

In [15]:
clean_v3.iloc[noise]

,BookID,Title,Author,Rating,Number of raters,5 stars,4 stars,3 stars,2 stars,1 star,Number of reviewers,Pages,PublishDate,Book format,Language,GenreLink,Series
9740,125303,A Doutrina De Buda: Siddharta Gautama,"Anonymous, Siddharta Gautama, Bukkyo Dendo Kyokai",4.26,24140,12726,6689,3440,825,460,967,200.0,January,Paperback,Portuguese,154391,NaN
15955,143086,Recogiendo Poemas,Jaime Sabines,4.51,218,141,51,24,1,1,13,77.0,Sa,Hardcover,Spanish,138021,NaN
21374,159148,The Secret Life of the Love Song and The Flesh...,Nick Cave,4.41,290,158,101,24,6,1,5,NaN,Pr,Audio CD,English,153610,NaN
21636,159964,The Dhammapada,"Anonymous, Ananda Maitreya, Thich Nhat Hanh",4.26,24139,12728,6686,3440,825,460,965,114.0,January,Paperback,English,154391,NaN
21640,159962,The Dhammapada,"Anonymous, Gautama Buddha, Eknath Easwaran",4.26,24140,12726,6689,3440,825,460,967,208.0,January,Paperback,English,154391,NaN
21641,159963,The Dhammapada: Verses on the Way,"Anonymous, Gautama Buddha, Glenn Wallis",4.26,24140,12726,6689,3440,825,460,967,224.0,January,Paperback,English,154391,NaN
21642,159961,The Dhammapada,"Anonymous, Gil Fronsdal, Jack Kornfield",4.26,24140,12726,6689,3440,825,460,967,152.0,January,Paperback,English,154391,NaN
21643,159966,The Dhammapada: The Sayings of the Buddha,"Anonymous, Gautama Buddha, Thomas Byrom",4.26,24140,12726,6689,3440,825,460,967,144.0,January,Hardcover,English,154391,NaN
21644,159965,The Dhammapada: The Path of Perfection,"Anonymous, Juan Mascaró",4.26,24140,12726,6689,3440,825,460,967,96.0,January,Paperback,English,154391,NaN
21645,159967,The Dhammapada: The Sayings of the Buddha,"Anonymous, Gautama Buddha, John Ross Carter",4.26,24140,12726,6689,3440,825,460,967,112.0,January,Paperback,English,154391,NaN
21646,159968,Dhammapada: The Sayings of Buddha,"Anonymous, Gautama Buddha, Thomas Cleary",4.26,24140,12726,6689,3440,825,460,967,144.0,January,Paperback,English,154391,NaN
21650,159969,Dhammapada: Annotated & Explained,"Anonymous, Gautama Buddha, F. Max Müller, Jack...",4.26,24140,12726,6689,3440,825,460,967,129.0,January,Paperback,English,154391,NaN
26134,174694,The Memoirs Of Cleopatra Part 3 Of 3,"Margaret George, Donada Peters",4.29,197,101,61,28,5,2,17,0.0,November,Audio Cassette,English,40856706,Memoirs of Cleopatra

In [17]:
clean_v3['PublishYear'] = year
clean_v3.head()

,BookID,Title,Author,Rating,Number of raters,5 stars,4 stars,3 stars,2 stars,1 star,Number of reviewers,Pages,PublishDate,Book format,Language,GenreLink,Series,PublishYear
0,3,Harry Potter and the Sorcerer's Stone,"J.K. Rowling, Mary GrandPré",4.48,7479780,4868903,1704361,631378,148016,127122,118557,309.0,June 26th 1997,Hardcover,English,4640799,Harry Potter,1997
1,1,Harry Potter and the Half-Blood Prince,J.K. Rowling,4.57,2567345,1738165,611768,175048,29134,13230,41832,652.0,July 16th 2005,Paperback,English,41335427,Harry Potter,2005
2,7,The Harry Potter Collection,"J.K. Rowling, Mary GrandPré",4.73,31236,25140,4473,1111,230,282,921,NaN,January 1st 2005,Paperback,English,21457570,Harry Potter,2005
3,10,Harry Potter Collection,J.K. Rowling,4.73,31236,25140,4473,1111,230,282,921,3342.0,January 1st 2005,Hardcover,English,21457570,Harry Potter,2005
4,5,Harry Potter and the Prisoner of Azkaban,"J.K. Rowling, Mary GrandPré",4.57,2993081,2028235,706012,215277,29265,14292,58998,435.0,July 8th 1999,Mass Market Paperback,English,2402163,Harry Potter,1999

In [28]:
clean_v4 = clean_v3[clean_v3.PublishYear.str.isdigit()]
len(clean_v3)

46556

In [33]:
clean_v4.PublishYear = clean_v4.PublishYear.astype(int)
clean_v4 = clean_v4.drop(columns=['PublishDate'])
clean_v4.tail()

,BookID,Title,Author,Rating,Number of raters,5 stars,4 stars,3 stars,2 stars,1 star,Number of reviewers,Pages,Book format,Language,GenreLink,Series,PublishYear
46556,99992,The Best American Science and Nature Writing 2000,"David Quammen, Burkhard Bilger",3.98,166,58,59,39,8,2,9,265.0,Paperback,English,96405,NaN,2000
46557,99990,The Best American Science and Nature Writing 2005,"Jonathan Weiner, Tim Folger",3.91,155,41,66,42,5,1,9,336.0,Paperback,English,96403,NaN,2005
46558,99991,The Best American Science and Nature Writing 2003,"Richard Dawkins, Tim Folger, Edward O. Wilson",4.13,195,83,66,37,6,3,7,352.0,Paperback,English,96404,NaN,2003
46559,99995,The Best American Science and Nature Writing 2000,"David Quammen, Burkhard Bilger",3.98,166,58,59,39,8,2,9,NaN,Hardcover,English,96405,NaN,2000
46560,99998,Best American Science and Nature Writing 2004,"Steven Pinker, Tim Folger",3.92,228,67,96,50,10,5,15,NaN,Hardcover,English,31789,NaN,2004

In [50]:
clean_v4.Pages.fillna(int(clean_v4.Pages.mean()), inplace=True)
clean_v4.Series.fillna('None', inplace=True)
clean_v4["Book format"].fillna(clean_v4["Book format"].mode(), inplace=True)
clean_v4.Language.fillna(clean_v4.Language.mode(), inplace=True)

clean_v4.tail()

,BookID,Title,Author,Rating,Number of raters,5 stars,4 stars,3 stars,2 stars,1 star,Number of reviewers,Pages,Book format,Language,GenreLink,Series,PublishYear
46556,99992,The Best American Science and Nature Writing 2000,"David Quammen, Burkhard Bilger",3.98,166,58,59,39,8,2,9,265.0,Paperback,English,96405,None,2000
46557,99990,The Best American Science and Nature Writing 2005,"Jonathan Weiner, Tim Folger",3.91,155,41,66,42,5,1,9,336.0,Paperback,English,96403,None,2005
46558,99991,The Best American Science and Nature Writing 2003,"Richard Dawkins, Tim Folger, Edward O. Wilson",4.13,195,83,66,37,6,3,7,352.0,Paperback,English,96404,None,2003
46559,99995,The Best American Science and Nature Writing 2000,"David Quammen, Burkhard Bilger",3.98,166,58,59,39,8,2,9,318.0,Hardcover,English,96405,None,2000
46560,99998,Best American Science and Nature Writing 2004,"Steven Pinker, Tim Folger",3.92,228,67,96,50,10,5,15,318.0,Hardcover,English,31789,None,2004

In [52]:
clean_v4.to_csv('goodreads/books_1.csv', index=False)

In [ ]:
def clean_data(data):
    clean_v1 = data[~data.GenreLink.isnull()]
    clean_v2 = clean_v1.drop_duplicates(subset="BookID")
    
    clean_v2["Raters"] = clean_v2.loc[:, ("5 stars", "4 stars", "3 stars", "2 stars", "1 star")].apply(sum, axis=1)
    clean_v3 = clean_v2[clean_v2["Raters"] > 150]
    
    publish = clean_v3.PublishDate
    year = publish.str.split().str[-1]
    clean_v3['PublishYear'] = year
    
    clean_v4 = clean_v3[clean_v3.PublishYear.str.isdigit()]