In [24]:
import pandas as pd
import numpy as np

In [25]:
data = pd.read_csv('goodreads/books_2.csv')

data.head()

,BookID,Title,Author,Rating,Number of raters,5 stars,4 stars,3 stars,2 stars,1 star,Number of reviewers,Pages,PublishDate,Book format,Language,GenreLink,Series,PublishYear
0,100001,Stephen Hawking's Universe,John Boslough,4.03,748,272,279,147,46,4,39,127.0,July 1st 1984,Paperback,English,6153,None,1984.0
1,100002,Beyond The Black Hole: Stephen Hawking's Universe,John Boslough,4.03,748,272,279,147,46,4,39,144.0,July 1st 1984,Hardcover,NaN,6153,None,1984.0
2,100005,In Search of Schrödinger's Cat,John Gribbin,4.05,18783,7027,6927,3753,800,276,473,302.0,September 1984,Paperback,English,96418,Schrödinger's Cat,1984.0
3,100006,Schrödinger's Kittens and the Search for Reali...,"John Gribbin, Mark Evan Chimsky",4.06,1500,534,601,300,48,17,60,272.0,1984,Paperback,English,208911,Schrödinger's Cat,1984.0
4,100015,Bahama Crisis,Desmond Bagley,3.63,461,79,181,157,38,6,21,296.0,January 1st 1981,Audio Cassette,English,96428,None,1981.0

In [26]:
len(data)

33560

In [27]:
clean_v1 = data[~data.GenreLink.isnull()]

len(clean_v1)

33560

In [28]:
clean_v2 = clean_v1.drop_duplicates(subset="BookID")
len(clean_v2)

33560

In [29]:
clean_v3 = clean_v2[clean_v2["Number of raters"] > 150]
len(clean_v3)

33560

In [30]:
publish = clean_v3.PublishDate
year = publish.str.split().str[-1]
year

0        1984
1        1984
2        1984
3        1984
4        1981
         ...
33555    1972
33556    1962
33557    2003
33558    1972
33559    1962
Name: PublishDate, Length: 33560, dtype: object

In [31]:
year.replace(list(year[~year.str.isdigit()]), np.NaN, inplace=True)

In [32]:
year.fillna(year.mode(), inplace=True)

In [33]:
clean_v3['PublishYear'] = year
clean_v3.head()

,BookID,Title,Author,Rating,Number of raters,5 stars,4 stars,3 stars,2 stars,1 star,Number of reviewers,Pages,PublishDate,Book format,Language,GenreLink,Series,PublishYear
0,100001,Stephen Hawking's Universe,John Boslough,4.03,748,272,279,147,46,4,39,127.0,July 1st 1984,Paperback,English,6153,None,1984
1,100002,Beyond The Black Hole: Stephen Hawking's Universe,John Boslough,4.03,748,272,279,147,46,4,39,144.0,July 1st 1984,Hardcover,NaN,6153,None,1984
2,100005,In Search of Schrödinger's Cat,John Gribbin,4.05,18783,7027,6927,3753,800,276,473,302.0,September 1984,Paperback,English,96418,Schrödinger's Cat,1984
3,100006,Schrödinger's Kittens and the Search for Reali...,"John Gribbin, Mark Evan Chimsky",4.06,1500,534,601,300,48,17,60,272.0,1984,Paperback,English,208911,Schrödinger's Cat,1984
4,100015,Bahama Crisis,Desmond Bagley,3.63,461,79,181,157,38,6,21,296.0,January 1st 1981,Audio Cassette,English,96428,None,1981

clean_v3.PublishYear = clean_v3.PublishYear.astype(int)
clean_v3 = clean_v4.drop(columns=['PublishDate'])
clean_v3.tail()

In [34]:
clean_v3.Pages.fillna(int(clean_v3.Pages.mean()), inplace=True)
clean_v3.Series.fillna('None', inplace=True)
clean_v3["Book format"].fillna(clean_v3["Book format"].mode(), inplace=True)
clean_v3.Language.fillna(clean_v3.Language.mode(), inplace=True)

clean_v3.drop(columns="PublishDate", inplace=True)

clean_v3.tail()

,BookID,Title,Author,Rating,Number of raters,5 stars,4 stars,3 stars,2 stars,1 star,Number of reviewers,Pages,Book format,Language,GenreLink,Series,PublishYear
33555,199993,The Steel Bonnets: The Story of the Anglo-Scot...,George MacDonald Fraser,3.99,651,234,229,142,39,7,79,416.0,Paperback,English,2422025,None,1972
33556,199989,The Reivers: A Reminiscence,William Faulkner,3.79,6673,1762,2550,1728,458,175,436,376.0,Hardcover,English,3127511,None,1962
33557,199992,Reiver's Bride,Amanda Scott,4.00,205,72,80,36,15,2,5,400.0,Paperback,English,193479,Secret Clan,2003
33558,199995,The Steel Bonnets: The Story of the Anglo Scot...,George MacDonald Fraser,3.99,651,234,229,142,39,7,79,361.0,Paperback,English,2422025,None,1972
33559,199998,The Reivers: Typescript Setting Copy,William Faulkner,3.79,6673,1762,2550,1728,458,175,436,416.0,Hardcover,English,3127511,None,1962

In [35]:
clean_v3.to_csv('goodreads/books_2.csv', index=False)

In [36]:
def clean_data(data):
    clean_v1 = data[~data.GenreLink.isnull()]
    clean_v2 = clean_v1.drop_duplicates(subset="BookID")
    clean_v3 = clean_v2[clean_v2["Number of raters"] > 150]
    
    publish = clean_v3.PublishDate
    year = publish.str.split().str[-1]
    year.replace(list(year[~year.str.isdigit()]), np.NaN, inplace=True)
    year.fillna(year.mode(), inplace=True)
    
    clean_v3['PublishYear'] = year
    
    clean_v3.Pages.fillna(int(clean_v3.Pages.mean()), inplace=True)
    clean_v3.Series.fillna('None', inplace=True)
    clean_v3["Book format"].fillna(clean_v3["Book format"].mode(), inplace=True)
    clean_v3.Language.fillna(clean_v3.Language.mode(), inplace=True)

    clean_v3.drop(columns="PublishDate", inplace=True)
    
    return clean_v3

In [37]:
for i in range(3, 9):
    file_name = 'goodreads/books_' + str(i) + '.csv'
    
    data = pd.read_csv(file_name)
    cleaned = clean_data(data)
    
    cleaned.to_csv(file_name, index=False)

<ipython-input-36-c45b511f6198>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_v3['PublishYear'] = year
c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-36-c45b511f6198>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_v3['PublishYear'] = year
c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-36-c45b511f6198>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_v3['PublishYear'] = year
c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-36-c45b511f6198>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_v3['PublishYear'] = year
c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(