# Getting Started

In [2]:
import random
import numpy as np
import pandas as pd
from copy import deepcopy

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils.random import sample_without_replacement
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

# Get Data

In [3]:
books = pd.read_csv('goodreads/books.csv')
genre = pd.read_csv('goodreads/genre.csv')

print(books.shape)
print(genre.shape)

(447991, 16)
(12019830, 3)

In [ ]:
books.head()

   BookID                                     Title  ...        Series  PublishYear
0       3     Harry Potter and the Sorcerer's Stone  ...  Harry Potter         1997
1       1    Harry Potter and the Half-Blood Prince  ...  Harry Potter         2005
2       7               The Harry Potter Collection  ...  Harry Potter         2005
3      10                   Harry Potter Collection  ...  Harry Potter         2005
4       5  Harry Potter and the Prisoner of Azkaban  ...  Harry Potter         1999

[5 rows x 16 columns]

In [ ]:
genre.head()

   GenreLink                           Genre  NumberOfPeople
0   17243229                             fix               1
1    1888943                      unfinished              11
2     940892                        borrowed              21
3       4417  het-contemporary-romance-books               1
4      67763                         to-read            1820

# Preprocess Data

In [ ]:
def get_genre_df(books, genre):
    links = books.GenreLink.unique().tolist()

    return genre[genre.GenreLink.isin(links)]

def get_genre(link, genre):
    return genre[genre.GenreLink == link]

In [ ]:
book_data = books[['BookID', 'Author', 'Rating', '5 stars',	'4 stars', '3 stars', '2 stars', '1 star', 'Number of reviewers', 'Pages', 'Book format', 'Language', 'PublishYear', 'GenreLink', 'Series']]
book_data.shape

(447991, 15)

In [ ]:
scaler = MinMaxScaler()
book_data[['Rating', '5 stars',	'4 stars', '3 stars', '2 stars', '1 star', 'Number of reviewers', 'Pages', 'PublishYear']] = scaler.fit_transform(book_data[['Rating', '5 stars',	'4 stars', '3 stars', '2 stars', '1 star', 'Number of reviewers', 'Pages', 'PublishYear']])

book_data.head()

   BookID                       Author  ...  GenreLink        Series
0       3  J.K. Rowling, Mary GrandPré  ...    4640799  Harry Potter
1       1                 J.K. Rowling  ...   41335427  Harry Potter
2       7  J.K. Rowling, Mary GrandPré  ...   21457570  Harry Potter
3      10                 J.K. Rowling  ...   21457570  Harry Potter
4       5  J.K. Rowling, Mary GrandPré  ...    2402163  Harry Potter

[5 rows x 15 columns]

# Calculate Distance

In [ ]:
def jaccard_dissimalirity(a_lst, b_lst):
    intersection = list(set(a_lst) & set(b_lst))
    union = list(set(a_lst) | set(b_lst))

    jaccard_sim = (1.0 * len(intersection))/len(union)

    return abs(1 - jaccard_sim)

def hamming_distance(a, b):
    if a == b:
        return 0
    
    return 1

def euclidian_distance(diff):
    diff2 = diff**2
    diff2_sum = diff2.sum(axis=1)
    
    return np.sqrt(np.float32(diff2_sum))

def cosine_dissimilarity(v_a, v_b):
    product = np.sum(v_a * v_b)
    length_product = np.sqrt(np.float32((v_a**2).sum())) * np.sqrt(np.float32((v_b**2).sum()))

    similarity = product/length_product
    return abs(1 - similarity)

In [ ]:
def book_difference1(books1, book2, genre1, genre2):
    numeric_cols = ['Rating', '5 stars', '4 stars', '3 stars', '2 stars', '1 star', 'Number of reviewers', 'Pages', 'PublishYear']
    rows = len(books1)

    numeric = books1[numeric_cols].to_numpy() - book2[numeric_cols].to_numpy()
    
    authors = book2.Author.strip('\"').split(', ')
    author_diff = np.zeros((rows, 1))
    for i in range(rows):
        book_author = books1.iloc[i].Author.strip('\"').split(', ')
        author_diff[i][0] = jaccard_dissimalirity(book_author, authors)

    lang_diff = (books1.Language != book2.Language).astype(int).to_numpy().reshape((rows, 1))
    format_diff = (books1['Book format'] != book2['Book format']).astype(int).to_numpy().reshape((rows, 1))

    series_diff = np.ones((rows, 1))
    if book2.Series != "none":
        series_diff = (books1.Series != book2.Series).astype(int).to_numpy().reshape((rows, 1))

    tags = genre2.Genre.unique().tolist()
    tag_diff = np.zeros((rows,1))
    for i in range(rows):
        book_tags = genre1[genre1.GenreLink == books1.iloc[i].GenreLink].Genre.unique().tolist()
        tag_diff[i][0] = jaccard_dissimalirity(book_tags, tags)

    diff = np.append(numeric, author_diff, axis=1)
    diff = np.append(diff, lang_diff, axis=1)
    diff = np.append(diff, format_diff, axis=1)
    diff = np.append(diff, series_diff, axis=1)
    diff = np.append(diff, tag_diff, axis=1)

    return euclidian_distance(diff)

# Recommendation System

In [ ]:
class BookRecommender:
    def __init__(self, distance):
        self.distance = distance

    def set_dataset(self, books, genre):
        self.books = books
        self.genre = genre

    def recommend(self, client, cli_genre):
        client_size = len(client)
        rec = np.zeros((len(self.books), client_size)) 
        
        for i in range(client_size):
            rec[:, i] = self.distance(self.books, client.iloc[i], self.genre, cli_genre)

        return rec 

    def get_recommendations(self, client, cli_genre, ind, k):
        rec = self.recommend(client, cli_genre)[:, ind]
        rec_sorted = np.argsort(rec)

        rec_ind = rec_sorted[:k]

        return self.books.iloc[rec_ind]

In [ ]:
sample_ind = sample_without_replacement(len(books), 300)
sample_data = book_data.iloc[sample_ind]

sample_data

         BookID  ...           Series
109834   305438  ...      Cape Refuge
416670  1808223  ...   The Elric Saga
774        1436  ...             None
353672  1408837  ...             None
368954  1488575  ...             None
...         ...  ...              ...
353559  1408360  ...             None
228106   842432  ...             None
138318   422306  ...  Adèle Blanc-Sec
321408  1239887  ...             None
332731  1295214  ...             None

[300 rows x 15 columns]

In [ ]:
cli_ind = sample_without_replacement(len(books), 20)
cli_books = book_data.iloc[cli_ind]

cli_books

         BookID  ...                                        Series
245193    12786  ...                                          None
374170   224439  ...                                          None
320228  1233661  ...                                          None
157535   921122  ...                                   Petwatching
49530    107295  ...                                          None
261852   967762  ...                                          None
412140  1781838  ...                                          None
265375   981869  ...                                Gotrek & Felix
346678  1373680  ...                                          None
282535  1057619  ...                                          None
118057   339423  ...                                          None
225516   833962  ...                                          None
313855  1201140  ...                                          None
265190   980884  ...  The Chronicles of Narnia (Publication Order)
441547  1955985  ...                                          None
313501  1199286  ...                                          None
278061  1037021  ...                                          None
285771  1072011  ...                                          None
19055     36203  ...                                          None
158361   515503  ...                                          None

[20 rows x 15 columns]

In [ ]:
sample_gen = get_genre_df(sample_data, genre)
cli_gen = get_genre_df(cli_books, genre)

In [ ]:
recommender = BookRecommender(book_difference1)
recommender.set_dataset(sample_data, sample_gen)

recommender.recommend(cli_books, cli_gen)

array([[1.71120071, 1.72702813, 1.98224497, ..., 1.70527232, 1.70441806,
        1.71663857],
       [1.69855654, 1.70940924, 1.9712075 , ..., 1.69557023, 1.7053349 ,
        1.70817399],
       [1.3949424 , 1.4130373 , 1.71717525, ..., 1.38999391, 1.39571512,
        1.04814291],
       ...,
       [1.7137394 , 1.71873009, 1.9841181 , ..., 1.7140367 , 1.73530364,
        1.73075199],
       [1.70734537, 1.72010183, 1.97875011, ..., 1.70286751, 1.70852041,
        1.71092772],
       [1.41416943, 1.43565369, 1.73234236, ..., 1.40547848, 1.39933062,
        1.41804755]])

In [ ]:
cli_books.iloc[17]

BookID                       1072011
Author                 Denis Johnson
Rating                      0.657321
5 stars                  0.000313089
4 stars                   0.00108798
3 stars                   0.00104211
2 stars                  0.000767332
1 star                   0.000530699
Number of reviewers       0.00291144
Pages                     0.00791892
Book format                Paperback
Language                     English
PublishYear                 0.762601
GenreLink                    2280133
Series                          None
Name: 285771, dtype: object

In [ ]:
recommender.get_recommendations(cli_books, cli_gen, 17, 5)

         BookID                            Author  ...  GenreLink  Series
209406   762107               F. Scott Fitzgerald  ...    2432116    None
279776  1045672                      Paulo Coelho  ...   13855759    None
157027   509199                     George Orwell  ...    1171545    None
141679   437367  William Shakespeare, Emrys Jones  ...     717119    None
263327   973507                       Dan Simmons  ...    1623747    None

[5 rows x 15 columns]

# Recommendation System with Clustering

In [ ]:
class KMedoids:
    def __init__(self, distance, frequency_calculator, sample_frequency, get_medoid, k = 3):
        self.k = k

        self.distance = distance
        self.frequency_calculator = frequency_calculator
        self.sample_frequency = sample_frequency
        self.get_medoid = get_medoid


    def get_genre(self, row, medoid=False):
        if medoid:
            return self.medoid_genre[self.medoid_genre.GenreLink == row.GenreLink]

        return self.corpus[self.corpus.GenreLink == row.GenreLink]
        

    def get_genre_df(self, data):
        links = data.GenreLink.unique().tolist()

        return self.corpus[self.corpus.GenreLink.isin(links)]

        
    def fit(self, data, tags, epoch=1000):
        self.dataset = data
        self.corpus = tags

        self.rows = len(self.dataset)
        
        # Step 1: Get medoids
        medoid_inds = []

        for i in range(self.k):
            medoid_ind = random.choice(range(self.rows))

            while medoid_ind in medoid_inds:
                medoid_ind = random.choice(range(self.rows))

            medoid_inds.append(medoid_ind)

        self.medoids = self.dataset.iloc[medoid_inds].reset_index(drop=True)
        self.medoid_genre = self.get_genre_df(self.medoids)
        print("Step 1 finished")
        #print(self.medoids)

        error = np.ones(self.k)
        self.dataset['label'] = -1

        count = 1
        while (error.any() != 0) and (count < epoch):
            # Step 2: Distance
            # Cluster labels for each point
            labels = np.array([-1 for x in range(self.rows)])

            # Distances to each medoid
            distances = np.zeros(self.k)

            # Frequency for mode
            frequency = [deepcopy(self.sample_frequency) for x in range(self.k)]

            # Calculate distance to each medoid
            for i in range(self.rows):
                cluster = -1
                row = self.dataset.iloc[i]
                gen = self.get_genre(row)

                for j in range(self.k):
                    medoid = self.medoids.iloc[j]
                    medoid_genre = self.get_genre(medoid, True)
                    distances[j] = self.distance(row, medoid, gen, medoid_genre)
                
                #print(distances)
                cluster = np.argmin(distances)
                    
                labels[i] = cluster
                frequency[cluster] = self.frequency_calculator(row, gen, frequency[cluster])
                
            self.dataset['label'] = labels
            print("Step 2." + str(count) + " finished.")
            #print(self.medoids)

            # Step 3: Update medoids
            medoid_ids = []
            for i in range(self.k):
                new_medoid_id = -1
                proposed_medoid, proposed_genre = self.get_medoid(frequency[i])
                new_medoid = proposed_medoid
                new_medoid_genre = proposed_genre
                best_distance = 1000

                #print("Start step 3")
                labelset = self.dataset[self.dataset.label == i].reset_index(drop=True)

                for j in range(len(labelset)):
                    row = labelset.iloc[j]
                    gen = self.get_genre(row)

                    current_dist = self.distance(proposed_medoid, row, proposed_genre, gen)
                    
                    if current_dist < best_distance:
                        new_medoid_id = row.BookID
                        new_medoid = row
                        new_medoid_genre = gen
                        best_distance = current_dist
                            
                medoid_ids.append(new_medoid_id) 
                error[i] = self.distance(new_medoid, self.medoids.iloc[i], new_medoid_genre, self.get_genre(self.medoids.iloc[i], True))

            #print(medoid_ids)
            print(error)
            print(self.dataset.groupby('label').BookID.count().to_numpy())

            self.medoids = self.dataset[self.dataset.BookID.isin(medoid_ids)].reset_index(drop=True)
            self.medoid_genre = self.get_genre_df(self.medoids)

            print("Step 3." + str(count) + " finished.")
            #print("Iteration: " + str(count))
            #print(self.medoids)

            count += 1


    def inertia(self):
        total_distance = 0.0

        for i in range(self.k):
            medoid = self.medoids.iloc[i]
            medoid_genre = self.get_genre(medoid, True)
            labelset = self.dataset[self.dataset.label == i].reset_index(drop=True)

            for ind in range(len(labelset)):
                row = labelset.iloc[ind]
                total_distance += self.distance(medoid, row, medoid_genre, self.get_genre(row))

        return total_distance

    
    def predict(self, data, genre):
        distances = np.zeros(self.k)

        for j in range(self.k):
            medoid = self.medoids.iloc[j]
            medoid_genre = self.get_genre(medoid, True)

            distances[j] = self.distance(data, medoid, genre, medoid_genre)

        result = np.argmin(distances)
        
        return result

    
    def predict_df(self, data, genre):
        result = np.array([-1 for x in range(len(data))])
        #print(self.medoids)
        
        for i in range(len(data)):
            distances = np.zeros(self.k)
            row = data.iloc[i]
            gen = genre[genre.GenreLink == row.GenreLink]

            result[i] = self.predict(row, gen)
        
        return result

    
    def get_labels(self):
        return self.dataset.label

    
    def get_medoids(self):
        return self.medoids


    def get_medoid_genre(self):
        return self.medoid_genre

In [ ]:
def clustering_distance(book1, book2, gen1, gen2):
    distance = 0.0

    authors1 = book1.Author.strip('\"').split(', ')
    authors2 = book2.Author.strip('\"').split(', ')
    distance += jaccard_dissimalirity(authors1, authors2)

    if book2.Series != "None" and book2.Series == book1.Series:
        distance += 1

    tags1 = gen1.Genre.unique().tolist()
    tags2 = gen2.Genre.unique().tolist()
    distance += jaccard_dissimalirity(tags1, tags2)

    return distance

def get_frequency(book, genre, cluster):
    cluster['info'] = cluster['info'].append(book[['Author', 'Series']])
    cluster['tags'] = cluster['tags'].append(genre[['GenreLink', 'Genre']])

    return cluster

def get_mode(cluster):
    new_centroid = pd.Series()

    new_centroid['Author'] = cluster['info'].Author.mode()[0]
    new_centroid['Series'] = cluster['info'].Series.mode()[0]

    length = cluster['tags'].groupby('GenreLink').size().mode()[0]
    sorted_tags = cluster['tags'].groupby('Genre', as_index=False).size().sort_values(by='size', ascending=False)
    new_genre = sorted_tags.iloc[:length]

    return (new_centroid, new_genre)

sample_frequency = {'info': pd.DataFrame(columns=['Author', 'Series']), 'tags': pd.DataFrame(columns=['GenreLink', 'Genre'])}

In [ ]:
sample_ind2 = sample_without_replacement(len(books), 500)
sample_data2 = book_data.iloc[sample_ind2]

sample_data2

         BookID  ... Series
356816  1423018  ...   None
154805   498162  ...   None
364410  1462934  ...   None
199220   704390  ...   None
77358    189929  ...   None
...         ...  ...    ...
373728  1515973  ...   None
77162    189183  ...   None
271976  1011172  ...   None
173565   576171  ...   None
404792  1734501  ...   None

[500 rows x 15 columns]

In [ ]:
cli_ind2 = sample_without_replacement(len(books), 50)
cli_books2 = book_data.iloc[cli_ind2]

cli_books2.head()

         BookID                 Author  ...  GenreLink     Series
128268   381325            Mike Ashley  ...    1827316       None
447971  1999849             Miyuki Eto  ...    2003668  Hell Girl
122332   357938  Carol de Chellis Hill  ...     348077       None
325433  1259177           V.C. Andrews  ...     386924      Logan
303685  1153229      Vonda N. McIntyre  ...    1140716       None

[5 rows x 15 columns]

In [ ]:
sample_gen2 = get_genre_df(sample_data2, genre)
cli_gen2 = get_genre_df(cli_books2, genre)

In [ ]:
model = KMedoids(clustering_distance, get_frequency, sample_frequency, get_mode, 5)
model.fit(sample_data2, sample_gen2, 5)

model.inertia()

Step 1 finished
Step 2.1 finished.
[1.83529412 1.85276074 1.94186047 1.875      1.8164557 ]
[354  70  15  24  37]
Step 3.1 finished.
Step 2.2 finished.
[1.81097561 1.87719298 1.         1.84705882 1.        ]
[ 21 104  18 165 192]
Step 3.2 finished.
Step 2.3 finished.
[0.         1.         1.84883721 0.         1.        ]
[241  19  48  19 173]
Step 3.3 finished.
Step 2.4 finished.
[0. 1. 0. 1. 1.]
[243  19  19 205  14]
Step 3.4 finished.

917.0713347729705

In [ ]:
model.predict_df(cli_books2, cli_gen2)

array([3, 3, 3, 3, 3, 3, 0, 4, 0, 3, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 1,
       2, 0, 0, 0, 0, 3, 3, 0, 0, 0, 1, 3, 0, 3, 0, 3, 0, 3, 0, 0, 3, 3,
       0, 0, 0, 3, 3, 3])

# Combination

In [ ]:
class KBookRecommender:
    def __init__(self, distance, distance_k, frequency_calculator, sample_frequency, get_medoid, k = 3):
        self.distance = distance
        self.KMedoids = KMedoids(distance_k, frequency_calculator, sample_frequency, get_medoid, k)


    def set_dataset(self, books, genre, size, epoch=10):
        self.books = books
        self.genre = genre

        batch_ind = sample_without_replacement(len(self.books), size)
        batch = self.books.iloc[batch_ind]
        batch_gen = get_genre_df(batch, self.genre)

        self.KMedoids.fit(batch, batch_gen, epoch)
        self.books['label'] = self.KMedoids.predict_df(self.books, self.genre)


    def calc_distance(self, client):
        books = self.books[self.books.label == client.label]

        return self.distance(books, client)


    def recommend(self, client, cli_genre, k):
        client_size = len(client)
        rec = np.zeros((len(self.books), client_size)) 

        client['label'] = self.KMedoids.predict(client, cli_genre)
        rec = self.calc_distance(client)
        rec_sorted = np.argsort(rec)
        rec_ind = rec_sorted[:k]

        labelset = self.books[self.books.label == client.label].reset_index(drop=True)

        return labelset.iloc[rec_ind]

In [ ]:
def book_difference2(books1, book2):
    numeric_cols = ['Rating', '5 stars', '4 stars', '3 stars', '2 stars', '1 star', 'Number of reviewers', 'Pages', 'PublishYear']
    rows = len(books1)

    numeric = books1[numeric_cols].to_numpy() - book2[numeric_cols].to_numpy()
    lang_diff = (books1.Language != book2.Language).astype(int).to_numpy().reshape((rows, 1))
    format_diff = (books1['Book format'] != book2['Book format']).astype(int).to_numpy().reshape((rows, 1))

    diff = np.append(numeric, lang_diff, axis=1)
    diff = np.append(diff, format_diff, axis=1)

    return euclidian_distance(diff)

In [ ]:
sample_ind3 = sample_without_replacement(len(books), 10000)
sample_data3 = book_data.iloc[sample_ind3]

sample_data3.head()

         BookID             Author  ...  GenreLink               Series
7328      13376       Nancy Farmer  ...     868252       Matteo Alacran
429861  1885287       Liz Fielding  ...   24883393  The Beaumont Brides
436190  1115279         G.A. Henty  ...    1926985                 None
83437    212855           Ann Wroe  ...     206046                 None
134983   409599  Katherine Neville  ...    1105501                 None

[5 rows x 15 columns]

In [ ]:
cli_ind3 = sample_without_replacement(len(books), 200)
cli_books3 = book_data.iloc[cli_ind3]

cli_books3.head()

         BookID  ...                Series
373972  1517307  ...                  None
37290     77242  ...                  None
428269  1876184  ...  The Ebenezum Trilogy
110252   307264  ...    Nuala Anne McGrail
346220  1371280  ...                  None

[5 rows x 15 columns]

In [ ]:
sample_gen3 = get_genre_df(sample_data3, genre)
cli_gen3 = get_genre_df(cli_books3, genre)

In [ ]:
krecommender = KBookRecommender(book_difference2, clustering_distance, get_frequency, sample_frequency, get_mode, 10)
krecommender.set_dataset(sample_data3, sample_gen3, 2000, 5)

Step 1 finished
Step 2.1 finished.
[1.58741259 1.87857143 1.82051282 1.53623188 1.6442953  1.71428571
 1.8707483  1.91489362 1.7607362  1.94915254]
[632  22  97 525 239 111  11   6 339  18]
Step 3.1 finished.
Step 2.2 finished.
[1.87272727 0.         1.89473684 0.         0.         1.
 0.         0.80625    1.         0.        ]
[323  49  10  11  45 790 386  65 318   3]
Step 3.2 finished.
Step 2.3 finished.
[1.90977444 0.         1.90196078 0.         0.         1.
 0.         1.         0.         0.        ]
[ 38  25  64  44 459 691 341 308  27   3]
Step 3.3 finished.
Step 2.4 finished.
[0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
[ 30  27  46 483 697 344 308  22  41   2]
Step 3.4 finished.

In [ ]:
samp = cli_books3.iloc[20]
samp_gen = get_genre(samp.GenreLink, cli_gen3)

In [ ]:
krecommender.recommend(samp, samp_gen, 10)

       BookID                               Author  ...               Series  label
908    773278               Ruth Lercher Bornstein  ...                 None      6
21     703193                           Fiona Watt  ...     That's Not My...      6
679    644935  Phil Roxbee Cox, Stephen Cartwright  ...                 None      6
1172   815234                Audrey Wood, Don Wood  ...                 None      6
214    312187             Fiona Watt, Rachel Wells  ...     That's Not My...      6
1368  1005366                          Lois Lenski  ...            Mr. Small      6
1370   313335                       Richard Scarry  ...                 None      6
281   1885410                      Bill Martin Jr.  ...  Bill Martin's Bears      6
353    315129   Laura Joffe Numeroff, Felicia Bond  ...       If You Give...      6
1419  1841494                          Keiko Kasza  ...                 None      6

[10 rows x 16 columns]